name: Build and Release macOS DMG

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0, v2.1.3 etc.

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'  # Change to your Xcode version if needed

    - name: Build app with xcodebuild
      run: |
        xcodebuild clean build \
          -project MacInternetSpeedMeater.xcodeproj \
          -scheme MacInternetSpeedMeater \
          -configuration Release \
          -derivedDataPath build

    - name: Set APP_PATH env variable
      run: echo "APP_PATH=$(pwd)/build/Build/Products/Release/MacInternetSpeedMeater.app" >> $GITHUB_ENV

    - name: Create DMG from app bundle
      run: |
        mkdir -p dmg
        hdiutil create dmg/MacInternetSpeedMeater.dmg \
          -volname "MacInternetSpeedMeater" \
          -srcfolder "$APP_PATH" \
          -ov -format UDZO

    - name: Publish DMG to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dmg/MacInternetSpeedMeater.dmg
      env:
        ANBU_TOKEN: ${{ secrets.ANBU_TOKEN }}
